### ISSUE TITLE
runtime: I/O loop panic

### ISSUE THREAD

**Issue by tsavola** [gate-computer/gate#39]
```
panic: runtime error: index out of range [0] with length 0

goroutine 30 [running]:
github.com/tsavola/gate/internal/file.pwritev(0x5, 0xc00049ffa0, 0x2, 0x2, 0xffffffffffffffff, 0x0, 0x0)
	gate/internal/file/writev_linux.go:53 +0x419
github.com/tsavola/gate/internal/file.writev(...)
	gate/internal/file/writev_linux.go:17
github.com/tsavola/gate/internal/file.(*File).WriteVec(...)
	gate/internal/file/file.go:41
github.com/tsavola/gate/runtime.subjectWriteLoop.func1(0xc000136010, 0xc0001245a0)
	gate/runtime/io.go:345 +0x18b
created by github.com/tsavola/gate/runtime.subjectWriteLoop
	gate/runtime/io.go:332 +0x67
```

**Comment by tsavola** [comment]
Not occurring anymore...
